# Generated by Django 5.2.9 on 2026-05-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mkt", "0002_ad_content_type_ad_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="field1",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
