# Generated by Django 5.2.9 on 2026-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mkt", "0003_ad_field1"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="field2",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
