# Generated by Django 5.2.9 on 2026-05-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mkt", "0005_comment_ad_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="field3",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
