# Generated by Django 5.2.9 on 2026-06-09 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mkt", "0007_fav_ad_favorites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_ads",
                through="mkt.Fav",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
